import type { SessionDigest } from "./digest.js";
import type { PublishedSessionBundle } from "./publish.js";
import type { Message, ToolCall } from "./types.js";

/** Render a published session bundle as deterministic GitHub-flavored Markdown. */
export function renderPublishedSessionMarkdown(bundle: PublishedSessionBundle): string
{
    const lines: string[] = [];
    renderFrontmatter(lines, bundle);

    const manifest = bundle.manifest;
    const digest = bundle.digest;
    lines.push(`# ${manifest.title}`);
    lines.push("");
    lines.push(`Generated by Session Bandit on ${manifest.generatedAt}.`);
    lines.push("");

    renderSource(lines, bundle);
    renderDigest(lines, digest);
    renderRelatedSessions(lines, bundle);
    renderSummaries(lines, digest);
    renderTranscript(lines, digest.transcript ?? bundle.session.messages);

    return lines.join("\n").trimEnd() + "\n";
}

function renderFrontmatter(lines: string[], bundle: PublishedSessionBundle): void
{
    const manifest = bundle.manifest;
    lines.push("---");
    lines.push(`title: ${yamlString(manifest.title)}`);
    lines.push(`slug: ${yamlString(manifest.slug)}`);
    lines.push(`generatedAt: ${yamlString(manifest.generatedAt)}`);
    lines.push(`agent: ${yamlString(manifest.source.agent)}`);
    lines.push(`sessionId: ${yamlString(manifest.source.sessionId)}`);
    lines.push(`redactionMode: ${yamlString(manifest.redaction.mode)}`);
    lines.push("---");
    lines.push("");
}

function renderSource(lines: string[], bundle: PublishedSessionBundle): void
{
    const source = bundle.manifest.source;
    lines.push("## Source");
    lines.push("");
    lines.push(`- Agent: ${source.agent}`);
    lines.push(`- Session ID: \`${source.sessionId}\``);
    if (source.project) { lines.push(`- Project: \`${source.project}\``); }
    if (source.model) { lines.push(`- Model: \`${source.model}\``); }
    lines.push(`- Started: ${source.startedAt || "(unknown)"}`);
    if (source.endedAt) { lines.push(`- Ended: ${source.endedAt}`); }
    lines.push(`- Redaction: ${bundle.manifest.redaction.mode}`);
    lines.push("");
}

function renderDigest(lines: string[], digest: SessionDigest): void
{
    lines.push("## Digest");
    lines.push("");
    lines.push(`- Substance: ${digest.substance.tier} (score ${digest.substance.score})`);
    lines.push(`- Tool calls: ${digest.substance.signals.toolCallCount}`);
    lines.push(`- Files written: ${digest.files.written.length}`);
    lines.push(`- Files read: ${digest.files.read.length}`);
    lines.push(`- Errors: ${digest.errors.length}`);
    lines.push(`- Tests run: ${digest.tests.length}`);
    if (digest.durationMin !== null) { lines.push(`- Duration: ${Math.round(digest.durationMin)} min`); }
    lines.push("");

    if (digest.keyTurns.goal)
    {
        lines.push("### Goal");
        lines.push("");
        lines.push(digest.keyTurns.goal);
        lines.push("");
    }

    if (digest.keyTurns.finalState.length > 0)
    {
        lines.push("### Final State");
        lines.push("");
        for (const item of digest.keyTurns.finalState)
        {
            lines.push(`- ${oneLine(item)}`);
        }
        lines.push("");
    }

    renderStringList(lines, "### Files Written", digest.files.written);
    renderStringList(lines, "### Files Read", digest.files.read);
    renderTests(lines, digest);
    renderErrors(lines, digest);
}

function renderRelatedSessions(lines: string[], bundle: PublishedSessionBundle): void
{
    const related = bundle.manifest.source.relatedSessions;
    if (related.length === 0) { return; }

    lines.push("## Related Sessions");
    lines.push("");
    for (const item of related)
    {
        const parts = [
            `${item.agent} ${item.kind}: \`${item.sessionId}\``,
            item.turnId ? `turn \`${item.turnId}\`` : undefined,
            item.path ? `path \`${item.path}\`` : undefined,
        ].filter((part): part is string => Boolean(part));
        lines.push(`- ${parts.join("; ")}`);
    }
    lines.push("");
}

function renderSummaries(lines: string[], digest: SessionDigest): void
{
    if (digest.summaries.length === 0) { return; }

    lines.push("## Summaries");
    lines.push("");
    for (const summary of digest.summaries)
    {
        lines.push(`### ${summaryLabel(summary.subtype)}`);
        lines.push("");
        if (summary.timestamp) { lines.push(`_Timestamp: ${summary.timestamp}_`); lines.push(""); }
        lines.push(summary.text);
        lines.push("");
    }
}

function renderTranscript(lines: string[], messages: Message[]): void
{
    lines.push("## Transcript");
    lines.push("");
    let transcriptIndex = 1;
    for (let i = 0; i < messages.length; i++)
    {
        const message = messages[i]!;
        if (message.role === "summary") { continue; }

        lines.push(`### ${transcriptIndex}. ${roleLabel(message)}`);
        transcriptIndex++;
        lines.push("");
        if (message.timestamp) { lines.push(`_Timestamp: ${message.timestamp}_`); lines.push(""); }
        if (message.text)
        {
            lines.push(message.text);
            lines.push("");
        }
        for (const toolCall of message.toolCalls)
        {
            renderToolCall(lines, toolCall);
        }
    }
}

function renderToolCall(lines: string[], toolCall: ToolCall): void
{
    lines.push("<details>");
    lines.push(`<summary>${escapeHtml(toolCall.name)} - ${toolCall.status}</summary>`);
    lines.push("");
    lines.push("Input:");
    lines.push("");
    lines.push("````json");
    lines.push(formatJson(toolCall.input));
    lines.push("````");
    lines.push("");
    if (toolCall.output)
    {
        lines.push("Output:");
        lines.push("");
        lines.push("````text");
        lines.push(toolCall.output);
        lines.push("````");
        lines.push("");
    }
    lines.push("</details>");
    lines.push("");
}

function renderStringList(lines: string[], title: string, values: string[]): void
{
    if (values.length === 0) { return; }
    lines.push(title);
    lines.push("");
    for (const value of values)
    {
        lines.push(`- \`${value}\``);
    }
    lines.push("");
}

function renderTests(lines: string[], digest: SessionDigest): void
{
    if (digest.tests.length === 0) { return; }
    lines.push("### Tests");
    lines.push("");
    for (const test of digest.tests)
    {
        const status = test.passed === null ? "unknown" : test.passed ? "pass" : "fail";
        lines.push(`- [${status}] \`${test.command}\``);
    }
    lines.push("");
}

function renderErrors(lines: string[], digest: SessionDigest): void
{
    if (digest.errors.length === 0) { return; }
    lines.push("### Errors");
    lines.push("");
    for (const error of digest.errors)
    {
        lines.push(`- ${error.name}${error.output ? `: ${oneLine(error.output)}` : ""}`);
    }
    lines.push("");
}

function summaryLabel(subtype: string): string
{
    switch (subtype)
    {
        case "memory":
            return "Session Memory";
        case "compaction":
            return "Context Summary";
        case "wrapped_codex":
            return "Original Codex Session";
        case "recap":
            return "Session Recap";
        default:
            return `Summary (${subtype})`;
    }
}

function roleLabel(message: Message): string
{
    return message.role.toUpperCase();
}

function formatJson(value: unknown): string
{
    try
    {
        return JSON.stringify(value, null, 2);
    }
    catch
    {
        return String(value);
    }
}

function oneLine(value: string): string
{
    return value.replace(/\s+/g, " ").trim();
}

function yamlString(value: string): string
{
    return JSON.stringify(value);
}

function escapeHtml(value: string): string
{
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}
