import type { DigestSummary, SessionDigest } from "./digest.js";
import type { PublishedSessionBundle } from "./publish.js";
import { slugify } from "./publish.js";
import type { RelatedSessionReference } from "./types.js";
import type { Message, ToolCall } from "./types.js";

/** Render a published session bundle as deterministic GitHub-flavored Markdown. */
export function renderPublishedSessionMarkdown(bundle: PublishedSessionBundle): string
{
    const lines: string[] = [];
    renderFrontmatter(lines, bundle);

    const manifest = bundle.manifest;
    const digest = bundle.digest;
    lines.push(`# ${manifest.title}`);
    lines.push("");
    lines.push(`Generated by Session Bandit on ${manifest.generatedAt}.`);
    lines.push("");

    renderTranscript(lines, digest.transcript ?? bundle.session.messages, bundle.session.model);
    renderSummaries(lines, digest);
    renderDigest(lines, digest);
    renderRelatedSessions(lines, bundle);
    renderSource(lines, bundle);

    return lines.join("\n").trimEnd() + "\n";
}

function renderFrontmatter(lines: string[], bundle: PublishedSessionBundle): void
{
    const manifest = bundle.manifest;
    lines.push("---");
    lines.push(`title: ${yamlString(manifest.title)}`);
    lines.push(`slug: ${yamlString(manifest.slug)}`);
    lines.push(`generatedAt: ${yamlString(manifest.generatedAt)}`);
    lines.push(`agent: ${yamlString(manifest.source.agent)}`);
    lines.push(`sessionId: ${yamlString(manifest.source.sessionId)}`);
    lines.push(`redactionMode: ${yamlString(manifest.redaction.mode)}`);
    lines.push("---");
    lines.push("");
}

function renderSource(lines: string[], bundle: PublishedSessionBundle): void
{
    const source = bundle.manifest.source;
    lines.push("## Source");
    lines.push("");
    lines.push(`- Agent: ${source.agent}`);
    lines.push(`- Session ID: \`${source.sessionId}\``);
    if (source.project) { lines.push(`- Project: \`${source.project}\``); }
    if (source.model) { lines.push(`- Model: \`${source.model}\``); }
    lines.push(`- Started: ${source.startedAt || "(unknown)"}`);
    if (source.endedAt) { lines.push(`- Ended: ${source.endedAt}`); }
    lines.push(`- Redaction: ${bundle.manifest.redaction.mode}`);
    lines.push("");
}

function renderDigest(lines: string[], digest: SessionDigest): void
{
    lines.push("## Digest");
    lines.push("");
    lines.push(`- Substance: ${digest.substance.tier} (score ${digest.substance.score})`);
    lines.push(`- Tool calls: ${digest.substance.signals.toolCallCount}`);
    lines.push(`- Files written: ${digest.files.written.length}`);
    lines.push(`- Files read: ${digest.files.read.length}`);
    lines.push(`- Errors: ${digest.errors.length}`);
    lines.push(`- Tests run: ${digest.tests.length}`);
    if (digest.durationMin !== null) { lines.push(`- Duration: ${Math.round(digest.durationMin)} min`); }
    lines.push("");

    if (digest.keyTurns.goal)
    {
        lines.push("### Goal");
        lines.push("");
        lines.push(digest.keyTurns.goal);
        lines.push("");
    }

    if (digest.keyTurns.finalState.length > 0)
    {
        lines.push("### Final State");
        lines.push("");
        for (const item of digest.keyTurns.finalState)
        {
            lines.push(`- ${oneLine(item)}`);
        }
        lines.push("");
    }

    renderStringList(lines, "### Files Written", digest.files.written);
    renderStringList(lines, "### Files Read", digest.files.read);
    renderTests(lines, digest);
    renderErrors(lines, digest);
}

function renderRelatedSessions(lines: string[], bundle: PublishedSessionBundle): void
{
    const related = bundle.manifest.source.relatedSessions;
    if (related.length === 0) { return; }

    lines.push("## Related Sessions");
    lines.push("");
    for (const item of related)
    {
        const parts = [
            `${item.agent} ${item.kind}: ${relatedSessionLink(item)}`,
            item.turnId ? `turn \`${item.turnId}\`` : undefined,
            item.path ? `path \`${item.path}\`` : undefined,
        ].filter((part): part is string => Boolean(part));
        lines.push(`- ${parts.join("; ")}`);
    }
    lines.push("");
}

function relatedSessionLink(item: RelatedSessionReference): string
{
    return `[${relatedSessionLabel(item)}](${relatedSessionHref(item)})`;
}

function relatedSessionLabel(item: RelatedSessionReference): string
{
    if (item.title) { return `${item.title} (\`${item.sessionId}\`)`; }
    return `\`${item.sessionId}\``;
}

function relatedSessionHref(item: RelatedSessionReference): string
{
    return `../${slugify(item.sessionId)}/`;
}

function renderSummaries(lines: string[], digest: SessionDigest): void
{
    if (digest.summaries.length === 0) { return; }

    lines.push("## Summaries");
    lines.push("");
    for (const summary of digest.summaries)
    {
        lines.push(`### ${summaryHeading(summary)}`);
        lines.push("");
        if (summary.timestamp) { lines.push(`_Timestamp: ${summary.timestamp}_`); lines.push(""); }
        lines.push(summary.text);
        lines.push("");
    }
}

function summaryHeading(summary: DigestSummary): string
{
    const related = summary.relatedSessions?.find((item) => item.kind === "sub_agent");
    if (!related) { return summaryLabel(summary.subtype); }

    const label = related.title ? `Sub-Agent Session: ${related.title}` : summaryLabel(summary.subtype);
    return `[${label}](${relatedSessionHref(related)})`;
}

function renderTranscript(lines: string[], messages: Message[], model: string | null): void
{
    // Keep structural changes mirrored in skill/templates/github-pages-default/.design/session-page.html.
    lines.push("<section class=\"published-transcript\" markdown=\"1\">");
    lines.push("");
    lines.push("## Session Transcript");
    lines.push("");
    for (let i = 0; i < messages.length; i++)
    {
        const message = messages[i]!;
        if (message.role === "summary" || shouldHideTranscriptMessage(message)) { continue; }
        if (message.text.trim())
        {
            renderMessageTurn(lines, message, model);
        }
        if (message.toolCalls.length > 0)
        {
            renderToolTurn(lines, message.toolCalls);
        }
    }
    lines.push("</section>");
    lines.push("");
}

function shouldHideTranscriptMessage(message: Message): boolean
{
    return message.role === "system" && message.subtype === "notice";
}

function renderMessageTurn(lines: string[], message: Message, model: string | null): void
{
    lines.push(`<section class="session-turn session-turn-${roleClass(message.role)}" markdown="1">`);
    lines.push("");
    lines.push(`### ${roleLabel(message)}`);
    lines.push("");
    const metadata = turnMetadata(message, model);
    if (metadata) { lines.push(`<p class="turn-timestamp">${escapeHtml(metadata)}</p>`); lines.push(""); }
    lines.push(normalizeMessageMarkdown(message.text));
    lines.push("");
    lines.push("</section>");
    lines.push("");
}

function normalizeMessageMarkdown(text: string): string
{
    const input = text.split("\n");
    const output: string[] = [];
    let inFence = false;

    for (let i = 0; i < input.length; i++)
    {
        const line = input[i]!;
        const isFence = /^\s*(```+|~~~+)/.test(line);
        if (!isFence)
        {
            output.push(line);
            continue;
        }

        const wasInFence = inFence;
        if (!wasInFence && output.length > 0 && output[output.length - 1]!.trim() !== "")
        {
            output.push("");
        }

        output.push(line);
        inFence = !inFence;

        const next = input[i + 1];
        if (wasInFence && next !== undefined && next.trim() !== "")
        {
            output.push("");
        }
    }

    return output.join("\n");
}

function turnMetadata(message: Message, model: string | null): string | null
{
    const parts: string[] = [];
    if (message.timestamp) { parts.push(message.timestamp); }
    if (message.role === "assistant" && model) { parts.push(model); }

    return parts.length > 0 ? parts.join(" · ") : null;
}

function renderToolTurn(lines: string[], toolCalls: ToolCall[]): void
{
    lines.push("<section class=\"session-turn session-turn-tools\" markdown=\"1\">");
    lines.push("");
    lines.push("### Tools");
    lines.push("");
    for (const toolCall of toolCalls)
    {
        renderToolCall(lines, toolCall);
    }
    lines.push("</section>");
    lines.push("");
}

function renderToolCall(lines: string[], toolCall: ToolCall): void
{
    lines.push("<details>");
    lines.push(`<summary>${escapeHtml(toolCall.name)} - ${toolCall.status}</summary>`);
    lines.push("");
    renderAgentRunLink(lines, toolCall);
    renderCodeBlock(lines, "Input:", "json", formatJson(toolCall.input));
    if (toolCall.output)
    {
        renderCodeBlock(lines, "Output:", "text", toolCall.output);
    }
    lines.push("</details>");
    lines.push("");
}

function renderAgentRunLink(lines: string[], toolCall: ToolCall): void
{
    const related = agentRunRelatedSession(toolCall);
    if (!related) { return; }

    lines.push(`<p>Sub-agent session: <a href="${escapeHtml(relatedSessionHref(related))}">${escapeHtml(related.title ?? related.sessionId)} (<code>${escapeHtml(related.sessionId)}</code>)</a></p>`);
    lines.push("");
}

function agentRunRelatedSession(toolCall: ToolCall): RelatedSessionReference | null
{
    if (toolCall.name !== "agent_run" || !toolCall.output) { return null; }

    const sessionId = agentRunSessionId(toolCall.output);
    if (!sessionId) { return null; }

    return {
        agent: "botbandit",
        kind: "sub_agent",
        sessionId,
        title: toolInputString(toolCall.input, "title"),
    };
}

function agentRunSessionId(output: string): string | null
{
    const outer = parseJson(output);
    const candidate = isRecord(outer) && typeof outer.value === "string" ? outer.value : output;
    const inner = parseJson(candidate);
    if (isRecord(inner) && typeof inner.subAgentId === "string") { return inner.subAgentId; }
    return null;
}

function parseJson(value: string): unknown
{
    try
    {
        return JSON.parse(value);
    }
    catch
    {
        return null;
    }
}

function toolInputString(input: unknown, key: string): string | undefined
{
    if (!isRecord(input)) { return undefined; }
    const value = input[key];
    return typeof value === "string" && value ? value : undefined;
}

function isRecord(value: unknown): value is Record<string, unknown>
{
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

function renderCodeBlock(lines: string[], label: string, language: string, value: string): void
{
    lines.push(`<p>${label}</p>`);
    lines.push(`<pre><code class="language-${language}">${escapeHtml(value)}</code></pre>`);
    lines.push("");
}

function renderStringList(lines: string[], title: string, values: string[]): void
{
    if (values.length === 0) { return; }
    lines.push(title);
    lines.push("");
    for (const value of values)
    {
        lines.push(`- \`${value}\``);
    }
    lines.push("");
}

function renderTests(lines: string[], digest: SessionDigest): void
{
    if (digest.tests.length === 0) { return; }
    lines.push("### Tests");
    lines.push("");
    for (const test of digest.tests)
    {
        const status = test.passed === null ? "unknown" : test.passed ? "pass" : "fail";
        lines.push(`- [${status}] \`${test.command}\``);
    }
    lines.push("");
}

function renderErrors(lines: string[], digest: SessionDigest): void
{
    if (digest.errors.length === 0) { return; }
    lines.push("### Errors");
    lines.push("");
    for (const error of digest.errors)
    {
        lines.push(`- ${error.name}${error.output ? `: ${oneLine(error.output)}` : ""}`);
    }
    lines.push("");
}

function summaryLabel(subtype: string): string
{
    switch (subtype)
    {
        case "memory":
            return "Session Memory";
        case "compaction":
            return "Context Summary";
        case "wrapped_codex":
            return "Original Codex Session";
        case "sub_agent":
            return "Sub-Agent Session";
        case "recap":
            return "Session Recap";
        default:
            return `Summary (${subtype})`;
    }
}

function roleLabel(message: Message): string
{
    switch (message.role)
    {
        case "system":
            return "System";
        case "tool":
            return "Tool";
        case "user":
            return "User";
        case "assistant":
            return "Assistant";
        case "summary":
            return summaryLabel(message.subtype ?? "summary");
    }
}

function roleClass(role: Message["role"]): string
{
    return role.replace(/[^a-z0-9_-]/gi, "-").toLowerCase();
}

function formatJson(value: unknown): string
{
    try
    {
        return JSON.stringify(value, null, 2);
    }
    catch
    {
        return String(value);
    }
}

function oneLine(value: string): string
{
    return value.replace(/\s+/g, " ").trim();
}

function yamlString(value: string): string
{
    return JSON.stringify(value);
}

function escapeHtml(value: string): string
{
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}
